title: New Memory Allocated
subtitle: delete [] ptr; void *ptr = 0;
url: "http://violapterin.blog"

markdown: kramdown
permalink: /:year/:title:output_ext
kramdown:
  math_engine: mathjax
  parse_block_html: false
use_math: true

defaults:
  scope:
    path: "assets/img"
  values:
    image: true
