title: New Memory Allocated
email: violapterin@gmail.com
description: > # (this ignores newlines)
  A science student, an amateur author, a curious composer, a luckless lad.
baseurl: "" # the subpath of the site
url: "http://violapterin.github.io" # the base hostname & protocol for your site
author: Violapterin
twitter_username: violapterin
github_username:  violapterin

markdown: kramdown
permalink: /:year/:title:output_ext
kramdown:
  math_engine: mathjax
  parse_block_html: false
use_math: true

defaults:
  scope:
    path: "assets/img"
  values:
    image: true
